apiVersion: v1
kind: Pod
metadata:
  name: time-check
spec:
  containers:
    - name: time-check
      image: busybox
      env:
        - name: TIME_FREQ
          valueFrom:
            configMapKeyRef:
              name: time-config
              key: TIME_FREQ
      command: ["bin/sh", "-c", "while true; do date; sleep $TIME_FREQ;done > /opt/time/time-check.log"]
      volumeMounts:
      - mountPath: "/opt/time"
        name: my-volume
  volumes:
    - name: my-volume
      emptyDir: {}