apiVersion: v1
kind: Pod
metadata:
  name: logger
spec:
  containers:
    - name: myfrontend
      image: nginx:alpine
      volumeMounts:
      - mountPath: "/var/www/nginx"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: log-claim